# Generated by Django 6.0.3 on 2026-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
